[package]
name = "os"
version = "0.1.0"
edition = "2024"
authors = ["Akaash Kashyap <akaashkashyap@gmail.com>"]

[dependencies]
bootloader = "0.9"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[bin]]
name = "os"
test = false
bench = false
